export const ENCUESTAS_KEY_IDS = {
  caracterizacionHogar: 1,
  caracterizacionVivienda: 2,
  caracterizacionFamiliar: 3,
};

export const CARACTERIZACION_HOGAR_KEY_IDS = {
  tenenciaViviendaCode: 1,
  recibioSubsidioVivienda: 2,
  familiaPoseeTierras: 3,
  tierraTieneEscrituraRegistrada: 4,
  familiaIncluidaProyectosProductivos: 5,
  tipoProyecto: 6,
  cantidadPersonasNucleoHogar: 7,
  cantidadDormitorios: 8,
  numeroHectareas: 18,
  departamentoId: 20,
  municipioId: 21,
  localidadId: 22,
  barrio: 23,
  direccion: 24,
  numeroTelefono: 25,
  jefeHogarNombreCompleto: 26,
  jefeHogarNumeroDocumento: 27,
};

export const CARACTERIZACION_FAMILIAR_KEY_IDS = {
  numeroTelefono: 54,
  tieneLibretaMilitar: 55,
  numeroDocumento: 56,
  tipoDocumentoCode: 57,
  apellidos: 58,
  nombres: 59,
  parentezcoCode: 61,
  fechaNacimiento: 64,
  sexo: 65,
  etnia: 66,
  esVictima: 67,
  tipoDiscapacidad: 68,
  programasSocialesEstado: 69,
  leeYEscribe: 71,
  ultimoTituloAcademico: 72,
  actualMenteEstudia: 73,
  nivelCursado: 76,
  gradoSemestre: 77,
  transporteEscolar: 79,
  alimentacionEscolar: 80,
  jovenesEnAccion: 81,
  familiasEnAccion: 82,
  creditoIcetex: 83,
  regimenSalud: 85,
  eps: 86,
  situacionActual: 88,
  papelDesempeniadoEmpresa: 89,
};

export const CARACTERIZACION_VIVIENDA_KEY_IDS = {
  documentoAcreditaPropiedad: 42,
  tipoVivienda: 43,
  materialPisos: 44,
  materialParedes: 45,
  materialTecho: 46,
  principalServicioSanitario: 47,
  tieneEnergiaElectrica: 91,
  tieneAcueducto: 92,
  tieneAlcantarillado: 93,
  tieneGasDomiciliario: 94,
  tieneRecoleccionBasura: 95,
};
