import { MODULES } from './principal';

export const ENC_AUTHORITIES = {
  CODE: MODULES.ENCUESTAS.CODE,
  BASICO: {
    CODE: MODULES.ENCUESTAS.SUBS.BASICO,
    REALIZAR: `${MODULES.ENCUESTAS.SUBS.BASICO}001`,
    MODIFICAR: `${MODULES.ENCUESTAS.SUBS.BASICO}002`,
  },
};
