export const __GEN__TRANSACC__ = {
  USUARIO: {
    CREAR: `GENUSU001`,
    MODIFICAR: `GENUSU002`,
    ACTUALIZAR_ESTADO: `GENUSU003`,
    CAMBIAR_ROL: `GENUSU004`,
    REINICIAR_PASSWORD: `GENUSU005`,
  },
};
